### ISSUE TITLE
SK1 Feedback

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-2017#32]
Feedback SK1

Selbstbericht:
- 2,5 CP Projektanteil als Anteil klar machen (fixed cn)
- 4.2.2 Erstsemesterbefragung -> Allgemeine Zufriedenheitsbefragung (fixed)
- FH -> TH (S.72)  (fixed cn)
- ProfiL2 (fixed cn)
- S.39 -> Wissenschaftlichkeit fehlt (fixed mw)
- S.83 -> Frau Sohn fehlt als Beauftragte (fixed cn)
- S.39 Qualifikationsziele besser differenzieren (fixed cn: nicht perfekt)
- S.75 letzter Absatz -> Qualitätsbeauftragter raus (fixed cn)
- interdisziplinäre Projektwoche // ggf. in Sem 4 -> (1,5) 

Modulhandbücher:
- Masterbeschreibungen glatt ziehen (fixed mw, aber nur für Projekte)
- Studierenden "sollte" -> "werden" (cn: hab ich nix gefunden zu. MW: sollen -> können, sind befähigt zu - immer vom "erfolgreichen" Studi ausgehen))
- Dedizierte Gewichtung der Prüfungsleistung (fixed mw, aber nur für Projekte)
- Medienformen -> raus oder optimieren, bislang nur Beamer, Folien und so (fixed mw, aber nur für Projekte)
- WPF im Master explizit machen (MW: ???)
- "Kennen", "verstehen" -> kann letztlich nicht überprüft werden, z.B. "AP2", was kann nicht geprüft werden, z.B: "AVM"

**Comment by martineisemann** [comment]
Hi Christian,

toll, dass das alles so gut geklappt hat. Hast du das passende PDF irgendwo hochgeladen, dass man nachschauen kann auf was sich z.B. S.39 bezieht?

Viele Grüße,
Martin

Am 3. März 2017 um 14:45:47, Christian Noss (notifications@github.com) schrieb:

Feedback SK1

Selbstbericht:

2,5 CP Projektanteil als Anteil klar machen
4.2.2 Erstsemesterbefragung -> Allgemeine Zufriedenheitsbefragung
FH -> TH (S.72) (fixed cn)
ProfiL2 (fixed cn)
S.39 -> Wissenaschaftlichkeit fehlt
S.83 -> Frau Sohn fehlt als Beauftragte
S.39 Qualifikationsziele besser differenzieren
S.75 letzter Absatz -> Qualitätsbeauftragter raus
interdisziplinäre Projektwoche // ggf. in Sem 4 -> (1,5)
Modulhandbücher:

Masterbeschreibungen glatt ziehen
Studierenden "sollte" -> "werden"
Dedizierte Gewichtung der Prüfungsleistung
Medienformen -> raus oder optimieren, bislang nur Beamer, Folien und so
WPF im Master explizit machen
"Kennen", "verstehen" -> kann letztlich nicht überprüft werden, z.B. "AP2", was kann nicht geprüft werden, z.B: "AVM"
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


__________________________________________

Prof. Dr.-Ing. Martin Eisemann
Computer Graphics and Computer Science

Technology
Arts Sciences
TH Köln

Technische Hochschule Köln
Campus Gummersbach
Steinmüllerallee 1
51643 Gummersbach
Raum 3.242

phone: +49 2261 8196 6378
e-mail: martin.eisemann@th-koeln.de
https://www.th-koeln.de/personen/martin.eisemann/
__________________________________________

**Comment by cnoss** [comment]
Ja, die Sachen liegen hier: https://github.com/th-koeln/mi-2017/tree/master/download/sk1
